version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: tjv
      POSTGRES_PASSWORD: tjv
      POSTGRES_DB: tjv_db
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data